package:
  name: fwdpy11
  version: "0.12.0"

source:
  url: https://files.pythonhosted.org/packages/71/1e/2b4b768f83bc9634bdc2faecdf58770407cb3b53b4dac13d8f643f442cd4/fwdpy11-0.12.0.tar.gz
  sha256: db57a77e2f0362a0f9beb5746203394833e17845bae242cfc9518043ed9d85b4

build:
  skip: True # [py27]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - pkgconfig
    - python
    - pip
    - numpy >=1.10
    - pybind11 >=2.6.0
    - tskit >=0.3.2
    - gsl
    - openblas
    - attrs
    - setuptools_scm
  run:
    - python
    - numpy >=1.10
    - tskit >=0.3.2
    - gsl
    - openblas
    - sparse
    - attrs
    - black

test:
  # Python imports
  imports:
    - fwdpy11

about:
  home: http://pypi.python.org/pypi/fwdpy11
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Forward-time population genetic simulation in Python.'

extras:
  identifiers:
    - 10.1534/genetics.114.165019
    - 10.1371/journal.pcbi.1006581
